#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class FairPriceCheck:
    def __init__(self, address, zipcode):
    
        self.address = address
        self.zipcode = zipcode
        
        #X1-ZWz1835knufc3v_38l6u
        #X1-ZWz1gtmiat11xn_7ew1d
        #X1-ZWz1fjckjdd8gb_a2eph

        KEY = "X1-ZWz16yet2q2wwb_8mfo0"

        from pyzillow.pyzillow import ZillowWrapper, GetDeepSearchResults, GetUpdatedPropertyDetails
        
        zillow_data = ZillowWrapper(KEY)
        
        deep_search_response = zillow_data.get_deep_search_results(address,zipcode, True)
        result = GetDeepSearchResults(deep_search_response)
        estimate = result.zestimate_amount
        ZID = result.zillow_id

        print(estimate)

        updated_property_details_response = zillow_data.get_updated_property_details(
        ZID)

        updated_results = GetUpdatedPropertyDetails(updated_property_details_response)
        list_price = (updated_results.price)
        print(list_price)

        fair = 0

        if estimate <= list_price:
            fair = 1
            print('Rip Off')
        else:
            print('Fair Price')
            
        self.fair = fair
        
    def return_fair(self):
        return fair

